### ISSUE TITLE
unityTask.Abort() doesn't stop tasks or ContinueOnUIThread

### ISSUE THREAD

**Issue by zkkzkk32312** [ClaytonIndustries/TaskParallel#1]
Tested using the example scene Manager Controller included in the package.

by changing the target number of ReturnAValueToTheUIThread() to a larger number,
and aborting it mid way resulting the number still gets printed on the UI canvas.

**Comment by ClaytonIndustries** [comment]
Fix in commit [74ebd9c](https://github.com/ClaytonIndustries/TaskParallel/commit/7a4e7d34e311990742371e337661458662624a2f)
