### ISSUE TITLE
(Question) Will threaded tasks started from the main thread continue to run in background on mobile? 

### ISSUE THREAD

**Issue by Gerfeso** [ClaytonIndustries/TaskParallel#2]
As title sates, when the Unity app is sent to the background on a mobile device will a new custom thread (not the main game or UI thread) continue to run in the background?

**Comment by ClaytonIndustries** [comment]
@Gerfeso that will depend on the mobile OS, for example if it's an android application code will not continue to run when the app is backgrounded
