### ISSUE TITLE
[Question] How can i use it in for loop

### ISSUE THREAD

**Issue by kazunetakeda25** [ClaytonIndustries/TaskParallel#3]

**Comment by ClaytonIndustries** [comment]
@reysantana gonna need some more information than this - what do you want to put in a loop?

**Comment by reysantana** [comment]
Hi @ClaytonIndustries 

Here are the details:

`
private async Task<Texture2D> DownloadImageTaskAsync(string url)
    {
        Debug.Log("function executed");
        using (UnityWebRequest unityWebRequest = UnityWebRequestTexture.GetTexture(url))
        {
            await unityWebRequest.SendWebRequest();

            Debug.Log("await passed");

            Texture2D contentTexture = null;

            if (!unityWebRequest.isHttpError && !unityWebRequest.isNetworkError)
            {
                contentTexture = DownloadHandlerTexture.GetContent(unityWebRequest);
                Debug.Log("image downloaded");
            }

            unityWebRequest.downloadHandler.Dispose();
            unityWebRequest.Dispose();
            Resources.UnloadUnusedAssets();

            return contentTexture;
        }
    }

    private byte[] ReadCacheImageData(string url)
    {
        Debug.Log("function executed");
        try
        {
            byte[] imageBytes = File.ReadAllBytes(url);
            Debug.Log("got bytes");
            return imageBytes;
        }
        catch (Exception)
        {
            return null;
        }
    }
    `
    
    After that, inside for loop, i call the function
    `
    string cacheFilePath = Path.Combine(Application.persistentDataPath, "images", fileName);
                if (File.Exists(cacheFilePath))
                {
                    UnityTask.Run(() =>
                    {
                        Debug.Log(cacheFilePath);
                        return ReadCacheImageData(cacheFilePath);
                    })
                    .ContinueOnUIThread((data) =>
                    {
                        Debug.Log(data);
                        byte[] imageData = (byte[])data.Result;
                        if (imageData != null)
                        {
                            Texture2D texture = new Texture2D(2, 2);
                            texture.LoadImage(imageData);
                            photo.texture = texture;
                            photo.GetComponent<AspectRatioFitter>().aspectRatio = (float)texture.width / (float)texture.height;

                            Resources.UnloadUnusedAssets();
                        }
                    });
                }
                else
                {
                    UnityTask.Run(() =>
                    {
                        Debug.Log(cacheFilePath);
                        return DownloadImageTaskAsync(products[i].image);
                    })
                    .ContinueOnUIThread(async (data) =>
                    {
                        Debug.Log(data);
                        Texture2D contentTexture = await data.Result;
                        if (contentTexture != null)
                        {
                            photo.texture = contentTexture;
                            photo.GetComponent<AspectRatioFitter>().aspectRatio = (float)contentTexture.width / (float)contentTexture.height;
                        }
                    });
                }
    `
    
    But I got this error:
    `
    NullReferenceException: Object reference not set to an instance of an object
CI.TaskParallel.UnityTask.RunOnUIThread (System.Action action) (at Assets/TaskParallel/UnityTask.cs:198)
CI.TaskParallel.Core.UnityUITask.Start () (at Assets/TaskParallel/Core/UnityUITask.cs:16)
CI.TaskParallel.UnityTask.<Initialise>b__9_0 () (at Assets/TaskParallel/UnityTask.cs:59)
System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Threading.ThreadHelper.ThreadStart () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEngine.<>c:<RegisterUECatcher>b__0_0(Object, UnhandledExceptionEventArgs)
    `

**Comment by ClaytonIndustries** [comment]
It's difficult to tell what it null in the RunOnUIThread callback - easiest way for you to find out is to put a breakpoint in there and step through until you find which object is null. (Just a note that your code to download the texture's is already running async on another thread so it doesn't really need wrapping in a UnityTast)

You can't chain WaitAll with RunOnUIThread
